---
- name: remove the iis web service
  hosts: windows

  tasks:
    - name: stop iis service
      win_service:
        name: W3Svc
        state: stopped

    - name: delete iis
      win_feature:
        name: Web-Server
        state: absent

    - name: delete website index.html
      win_file:
        path: C:\Inetpub\wwwroot\index.html
        state: absent
